# ZMK build matrix.
#
# Corne split keyboard on nice!nano v2.
include:
  - board: nice_nano_v2
    shield: corne_left
    artifact-name: trovatore-left
  - board: nice_nano_v2
    shield: corne_right
    artifact-name: trovatore-right